server:
  port: 9002

spring:
  application:
    # 在注册中心的项目名
    name: spring-cloud-config-client

eureka:
  instance:
    # eureka客户端定义服务续约时间
    lease-renewal-interval-in-seconds: 30
    instance-id: ${spring.application.name}:${random.int}
  client:
    serviceUrl:
      # 注册中心地址,default-zone: http://${name}:${password}@localhost:1111/eureka/
      defaultZone: http://localhost:1111/eureka/
    # 是否启用Eureka客户端，默认为true
    enabled: true
    # 是否将自身的实例信息注册到eureka服务器默认为true
    register-with-eureka: true
    # 是否从eureka服务器拉取注册信息，作为服务消费者，这个是必须的
    fetch-registry: true

#SpringBoot2.1之后，项目启动时，控制台不自动打印api了，需要做如下配置：更改 org.springframework.web 包的日志级别
logging:
  level:
    org.springframework.web: TRACE

#actuator监控端点
management:
  endpoints:
    web:
      #Web端点的基本路径,默认为/actuator
      base-path: /actuator
      #默认值访问health,info端点  用*可以包含全部端点
      exposure:
        include: "*"
